# Generated by Django 5.1.1 on 2024-09-11 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EM_ANALISE", "Em análise"),
                            ("ACEITO", "Aceito"),
                            ("EM_SEPARACAO", "Em separação"),
                            ("CANCELADO", "Cancelado"),
                            ("EM_PREPARO", "Em preparo"),
                            ("EM_TRANSITO", "Em trânsito"),
                            ("ENTREGUE", "Entregue"),
                        ],
                        default="Em análise",
                        max_length=255,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
